package demo.rules.experience;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Passenger implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	//@org.kie.api.definition.type.Label(value = "Prefix")
	private java.lang.String prefix;
	//@org.kie.api.definition.type.Label(value = "First Name")
	private java.lang.String firstName;
	//@org.kie.api.definition.type.Label(value = "Middle Name")
	private java.lang.String middleName;
	//@org.kie.api.definition.type.Label(value = "Sur Name")
	private java.lang.String surName;
	//@org.kie.api.definition.type.Label(value = "PCV")
	private long PCV;

	public Passenger() {
	}

	public java.lang.String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(java.lang.String prefix) {
		this.prefix = prefix;
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(java.lang.String middleName) {
		this.middleName = middleName;
	}

	public java.lang.String getSurName() {
		return this.surName;
	}

	public void setSurName(java.lang.String surName) {
		this.surName = surName;
	}

	public long getPCV() {
		return this.PCV;
	}

	public void setPCV(long PCV) {
		this.PCV = PCV;
	}

	public Passenger(java.lang.String prefix, java.lang.String firstName,
			java.lang.String middleName, java.lang.String surName, long PCV) {
		this.prefix = prefix;
		this.firstName = firstName;
		this.middleName = middleName;
		this.surName = surName;
		this.PCV = PCV;
	}

}